M48
; DRILL file {KiCad (6.0.8)} date Wed Nov  9 14:46:17 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-11-09T14:46:17+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X165.58Y-106.12
X171.36Y-106.12
T2
X118.8Y-85.5
X118.8Y-108.5
X176.8Y-85.5
X176.8Y-108.5
T0
M30
